# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliable', models.BooleanField(verbose_name='是否启用')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工区名称,必须唯一')),
                ('introduce', models.CharField(max_length=1000, verbose_name='介绍,不超过500个字')),
                ('process_discipline', models.ImageField(upload_to='process_discipline', verbose_name='工艺纪律检查图片')),
                ('important_change', models.ImageField(upload_to='important_change', verbose_name='重大更改或整改图片')),
                ('working_skill', models.ImageField(upload_to='working_skill', verbose_name='班组人员职责以及技能')),
                ('organize_framework', models.ImageField(upload_to='organize_framework', verbose_name='工区组织架构图')),
                ('working_skill_radar', models.ImageField(upload_to='working_skill_radar', verbose_name='人员技能统计图')),
                ('standbook', models.ImageField(upload_to='standbook', verbose_name='工位台账信息')),
                ('process_layout', models.ImageField(upload_to='process_layout', verbose_name='工区工艺布局图')),
                ('dagerous_map', models.ImageField(upload_to='dagerous_map', verbose_name='工位危险源地图')),
                ('improve_proposal', models.ImageField(upload_to='improve_proposal', verbose_name='改善提案图片')),
                ('attainment_rate', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='标准工位达标率,单位百分比')),
                ('pass_rate', models.ImageField(upload_to='pass_rate', verbose_name='当月一次性合格率统计')),
                ('exception', models.ImageField(upload_to='exception', verbose_name='当月异常情况')),
                ('typical_question', models.ImageField(upload_to='typical_question', verbose_name='典型质量问题')),
            ],
        ),
        migrations.CreateModel(
            name='AreaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, verbose_name='产品状态')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='状态')),
                ('validity_date', models.DateField(verbose_name='有效期')),
                ('equipment_check', models.ImageField(upload_to='equipment_check', verbose_name='设备点检')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Area', verbose_name='所在工区')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='状态')),
                ('remark', models.CharField(max_length=400, verbose_name='缺料统计')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('pic', models.ImageField(upload_to='product_pic', verbose_name='介绍图片')),
            ],
        ),
        migrations.CreateModel(
            name='ProductExecuting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True, verbose_name='计划日期')),
                ('plan', models.IntegerField(verbose_name='计划数量')),
                ('excuted', models.IntegerField(verbose_name='已生产数量')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Area', verbose_name='工区')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.Product', verbose_name='产品')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='productlist',
            field=models.ManyToManyField(to='screen.Product', verbose_name='能生产的产品列表'),
        ),
        migrations.AddField(
            model_name='area',
            name='statusNow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.AreaStatus', verbose_name='当前状态'),
        ),
    ]
