# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexecuting',
            name='isnew',
            field=models.BooleanField(default=True, verbose_name='是否新造'),
        ),
    ]
