# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_remove_productexecuting_new_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productexecuting',
            name='date',
        ),
    ]
