# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_auto_20160510_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productexecuting',
            name='produce_date',
            field=models.DateField(verbose_name='计划日期'),
        ),
    ]
