# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 05:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screen', '0007_auto_20160510_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '工区管理', 'verbose_name_plural': '工区管理'},
        ),
        migrations.AlterModelOptions(
            name='areastatus',
            options={'verbose_name': '工区状态管理', 'verbose_name_plural': '工区状态管理'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
        migrations.AlterModelOptions(
            name='productexecuting',
            options={'verbose_name': '生产计划管理', 'verbose_name_plural': '生产计划管理'},
        ),
        migrations.AddField(
            model_name='area',
            name='managerList',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='管理人员'),
        ),
        migrations.AlterField(
            model_name='area',
            name='avaliable',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
    ]
