# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0011_auto_20160513_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmanager',
            name='isProceed',
            field=models.BooleanField(default=False, verbose_name='已响应'),
        ),
    ]
